kind: Namespace
apiVersion: v1
metadata:
  name: test1
  labels:
    branch: test1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test1
  namespace: argocd
spec:
  project: default
  source:
    helm: 
      valueFiles:
        - ../../configurations/base/values.yaml
        - ../../configurations/dev/values.yaml
        - ../../configurations/test1/values.yaml
    path: charts/saca/
    repoURL: git@github.com:timur-nugaev/gitops-k8s-manifests.git
    targetRevision: test1
  destination:
    server: https://kubernetes.default.svc
    namespace: test1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    