build:
  enabled: true
branchName: test1
services:
  service2:
    image:
      tag: 07f0a6830f0fc066d00d5f5185b98877be1e86e5
  service1:
    expose: false
    image:
      tag: 5aa6d3c7b52ad15ec67d91a78accf68a00b18096
