kind: Namespace
apiVersion: v1
metadata:
  name: change-service1-http-reponse
  labels:
    branch: change-service1-http-reponse
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: change-service1-http-reponse
  namespace: argocd
spec:
  project: default
  source:
    helm: 
      valueFiles:
        - ../../configurations/base/values.yaml
        - ../../configurations/dev/values.yaml
        - ../../configurations/change-service1-http-reponse/values.yaml
    path: charts/saca/
    repoURL: git@github.com:timur-nugaev/gitops-k8s-manifests.git
    targetRevision: change-service1-http-reponse
  destination:
    server: https://kubernetes.default.svc
    namespace: change-service1-http-reponse
  syncPolicy: {}