apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-pre-prod
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 4
  target:
    kind: Deployment
    name: myapp   
- ../base
