kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: aqaliarept/test:{{ .Values.myapp.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    {{- if .Values.myapp.dns }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.myapp.dns }}
    {{- else }}  
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.branchName }}.example.com
    {{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx


