{{ $branch := .Values.branchName }}
{{ $imageRegistry := .Values.imageRegistry }}
{{ $dnsZone := .Values.dnsZone }}

{{ range $serviceName, $service := .Values.services }}
{{ if eq ($service.autoGenerate | default true) true }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      containers:
      - name: {{ $serviceName }}
        image: {{ $imageRegistry }}/{{ $serviceName }}:{{ $service.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
{{ if eq ($service.expose | default false) true }}
metadata:
  name: {{ $serviceName }}
  annotations:
  {{if $service.dns }}
    external-dns.alpha.kubernetes.io/hostname: {{ $service.dns }}
  {{ else }}
    external-dns.alpha.kubernetes.io/hostname: {{ $serviceName }}.{{ $branch }}.{{ $dnsZone }}
  {{ end }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ $serviceName }}
{{ else }}
metadata:
  name: {{ $serviceName }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ $serviceName }}
{{ end }}

---
{{ end }}
{{ end }}

