build:
  enable: false

dnsZone: test-scpp.dev

branchName: main
applicationName: qa

services:
  service1:
    image:
      tag: 945509f2b717fceaef30013249b9551fc3c193dd
      dns: sevice1.qa.test-scpp.dev
