kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: aqaliarept/test:REPLACEME
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
